services:
  - type: web
    name: lexora-api
    env: python
    region: oregon  # ou altere para o mais próximo de seus usuários
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
